name: myappflutter
description: "Meu app Flutter"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.5
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/images/lake.png
    - lib/images/lake1.jpg
    - lib/images/lake2.jpg
    - lib/images/lake3.jpg
    - lib/images/lake4.jpg  
    - lib/images/lake5.jpg  
    - lib/images/lake6.jpg
    
    
    
    
    

    

